
[package]
name = "sophia_benchmark"
version = "0.1.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]

[workspace]
members = [".", ]

[dependencies]
sophia = { git = "https://github.com/BruJu/sophia_rs" }
time = "*"
regex =  "1.3.4"

